### ISSUE TITLE
SQL View for 'Order By'

### ISSUE THREAD

**Issue by maduranga001** [redtempo/dnnstuff.sqlviewpro#2]
I just used an SQL and it was working. I just wanted to load the SQL with an order. Most recent one on top.

I used 'ORDER BY [Id] DESC' and it is not loading now. Giving an error.

is this not working for it?

I am using this data list to edit and delete options too.

Please, can you advise me?

Thank you very much for giving us this free module. A great one.
I have purchased this before and saw it is free now.

Thank you!

**Comment by richard-edwards** [comment]
Can you post your full sql clause please and I'll take a look.

**Comment by maduranga001** [comment]
Hi Richard,

Thank you for replying to address this issue.

`SELECT [Id]
,(select convert(varchar(11), [Activity_Date], 106) ) AS Activity_Date
      ,[Company_Name]
      ,[No_Volunteers]
      ,[Event_Desc]
,[images]
  FROM [dbo].[Corp_activities]
ORDER BY [Id] DESC `

**Comment by richard-edwards** [comment]
Do you have the sorting option turned on in the grid? If so, you can't include the ORDER BY option in the query itself, because that is dynamically added when a column is sorted. If you do have sorting enabled, you can specify the original sort order in the Order By setting in the sort section, but leave off the 'ORDER BY' piece because that is implied. In your case the 'Order By' setting would just be '[Id] DESC'.

**Comment by maduranga001** [comment]
Hi Richard,

I can not find a Sorting option on this module.
Where is it? I am using the DNNStuff - SQLViewPro 5.0.0 module.

**Comment by richard-edwards** [comment]
It is an option only on the grid report. If you edit the report, then click on the 'Report Type' tab you'll see all the options specific to that type of report (grid). There are sections for sorting, grouping and miscellaneous in there.

You are using a grid report correct?

**Comment by maduranga001** [comment]
Yes Richard.

Can't we Edit/Delete Records on this Grid type?

**Comment by richard-edwards** [comment]
No, SQLView Pro is only for presentation, has never had the ability to edit records.

**Comment by maduranga001** [comment]
Ok Richard. Thank You!

 I need to edit/Delete records too on this specific admin page. I used this module on other pages to view the template based data and was very useful.
It would be very interesting if it has add/edit feature too. For Grid type Reports.
