### ISSUE TITLE
Can't expand parameter?

### ISSUE THREAD

**Issue by WHairstonLOI** [redtempo/dnnstuff.sqlviewpro#7]
I'm sure I'm doing something wrong, but I'm driving myself absolutely insane trying to figure out why I can't get a simple query to expand parameters in v5.0.0.

My report query looks like this:
`SELECT [Members Name & Address].[FNAME], [Members Name & Address].[LNAME] 
FROM [Members Name & Address] 
WHERE (([Members Name & Address].[FNAME] = '[PARAMETER:FirstName]'));`

and I have a parameter named FirstName defined as a textbox.

When I execute the query with Debug enabled, the parameter does not expand to what is entered. For example, if I enter the name John into the FirstName textbox, the query expands to:
`SELECT [Members Name & Address].[FNAME], [Members Name & Address].[LNAME] 
FROM [Members Name & Address] 
WHERE (([Members Name & Address].[FNAME] = '@parameter_firstname'));`

Of course, this does NOT return any data from the database. I expected this to expand to:
`SELECT [Members Name & Address].[FNAME], [Members Name & Address].[LNAME] 
FROM [Members Name & Address] 
WHERE (([Members Name & Address].[FNAME] = 'John'));`

If I omit the single quotes around the [PARAMETER:FirstName] in the query, then the query doesn't even test correctly. I just get "Query may be invalid! : Data type mismatch in criteria expression." If I save it that way and attempt to run the report (entering any name in the FirstName parameter prompt), I get: 

`An error has occurred. DotNetNuke.Services.Exceptions.ModuleLoadException: No value given for one or more required parameters. ---> System.Data.OleDb.OleDbException: No value given for one or more required parameters. at System.Data.OleDb.OleDbCommand.ExecuteCommandTextErrorHandling(OleDbHResult hr) at System.Data.OleDb.OleDbCommand.ExecuteCommandTextForSingleResult(tagDBPARAMS dbParams, Object& executeResult) at System.Data.OleDb.OleDbCommand.ExecuteCommandText(Object& executeResult) at System.Data.OleDb.OleDbCommand.ExecuteCommand(CommandBehavior behavior, Object& executeResult) at System.Data.OleDb.OleDbCommand.ExecuteReaderInternal(CommandBehavior behavior, String method) at System.Data.OleDb.OleDbCommand.ExecuteReader(CommandBehavior behavior) at System.Data.OleDb.OleDbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior) at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior) at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior) at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, String srcTable) at DNNStuff.SQLViewPro.Services.Data.Query.RetrieveData(String queryText, String connectionString, String dataSetName, String srcTable, Int32 cacheTimeout, String cacheScheme, Hashtable parameters) at DNNStuff.SQLViewPro.Controls.ReportControlBase.ReportData(String query) at DNNStuff.SQLViewPro.StandardReports.GridReportControl.BindGridToData() at DNNStuff.SQLViewPro.StandardReports.GridReportControl.Page_Load(Object sender, EventArgs e) --- End of inner exception stack trace ---`

Can anyone shed any light on what I might be overlooking? It HAS to be something obvious, but I'm just not seeing it...

Thanks in advance,
Warren

**Comment by richard-edwards** [comment]
Hi Warren,

Do you have any other forms on the page, such as Action Form or a similar module?

**Comment by WHairstonLOI** [comment]
Hi Richard,

No Action Form or other modules on the page. This is a new page I'm developing for a client who has never used the SQLViewPro module previously. This is a DNN 8.0.4 site and I'm querying from a Microsoft Access .mdb database. I had simply created a new page (view restricted to administrators), dropped the SQLViewPro module on it, and setup the necessary connection, report set, report, parameters, etc. with a new installation of SQLViewPro 5.0.0.

I finally gave up on it last night and copied my query and connection strings to Notepad, uninstalled SQLViewPro 5.0.0, then installed an old copy of 4.1.1. Pasted the connection string, recreated the report set and parameter, pasted the query back in, and everything worked as expected.

Maybe sometime over the next couple of days, I can setup a test copy of the site and install SQLViewPro 5.0.0 over the currently-working solution to see if it still fails.

Thanks,
Warren

**Comment by anpa8** [comment]
Hi,
i've same problem with "@parameter_name". Tried to debug it in visual studio but can't find solution. Does the problem still exists?

**Comment by richard-edwards** [comment]
My apologies but I'm not maintaining this project any more. If you know someone who would like to take over the project have them get in touch with me and I'll transfer over. I'm actually not doing anything in the DNN space anymore.
